"""
LLM service.

This module is responsible for communicating with the AI model.

The rest of our application does not need to know how Groq works.
It simply calls the review_code() function and receives a
structured CodeReview object.
"""

from groq import Groq

from app.config import settings
from app.models import CodeReview


# Create the Groq client using the API key stored in our
# application configuration.
client = Groq(
    api_key=settings.groq_api_key
)


# Model used for code review.
#
# We keep the model name in one place so it can easily be
# changed later without modifying the review logic.
MODEL_NAME = "llama-3.3-70b-versatile"


# System prompt defines the role and behaviour of our AI reviewer.
SYSTEM_PROMPT = """
You are an expert software engineer performing a professional
code review of a GitHub pull request.

Your job is to identify genuine, actionable problems in the
changed code.

Focus primarily on:

1. Security vulnerabilities
2. Bugs and incorrect behaviour
3. Reliability problems
4. Performance problems
5. Maintainability problems that materially affect the code

Do NOT report minor stylistic preferences unless they create
a meaningful engineering problem.

IMPORTANT RULES:

- Only report issues that are supported by the provided diff.
- Do not invent problems that are not visible in the diff.
- Do not assume missing context unless the diff clearly requires it.
- Use the exact file path shown in the diff.
- Use the line number from the diff whenever possible.
- Do not invent or guess file names.
- Do not invent line numbers.
- If you cannot determine an accurate line number, use null.
- Do not report the same issue multiple times.
- Prioritise real security vulnerabilities over style issues.
- Only classify an issue as security-related when there is
  concrete evidence in the code.

SECRET HANDLING:

Environment files and configuration examples require special
attention.

A placeholder such as:

    GITHUB_TOKEN=your_github_token_here

is NOT a leaked credential and should NOT be reported as a
security vulnerability.

However, an actual credential, API key, password, token, or
secret value committed to source code SHOULD be reported as a
security issue.

CONFIGURATION:

Configuration fields that load values from environment variables
are not themselves security vulnerabilities.

For example:

    github_token: str

is not a hardcoded secret if the actual value is loaded from
the environment.

Do not report this as a security issue unless the secret value
itself appears in the source code.

QUALITY:

Do not report generic recommendations such as "add error handling"
unless there is a specific, realistic failure scenario visible
in the changed code.

Do not report missing error handling simply because a function
could theoretically fail.

SEVERITY:

Use these severity levels:

critical:
    Severe security vulnerabilities, credential exposure,
    remote code execution, or vulnerabilities that could cause
    major compromise.

high:
    Serious security vulnerabilities or bugs that could
    significantly affect the application.

medium:
    Important bugs, reliability problems, or meaningful
    maintainability issues.

low:
    Minor issues that are still actionable and worth addressing.

If there are no meaningful issues, return an empty issues list
and explain that no significant issues were identified.

Return ONLY valid JSON matching the requested schema.

OUTPUT SCHEMA:

You MUST use these exact field names.

Top-level fields:

{
    "summary": "...",
    "overall_risk": "...",
    "issues": [...],
    "recommendations": [...]
}

Each issue MUST have exactly these fields:

{
    "severity": "high",
    "category": "security",
    "file": "backend/app/example.py",
    "line": 10,
    "title": "Short issue title",
    "description": "Detailed explanation of the issue",
    "recommendation": "How to fix the issue"
}

IMPORTANT:

- The issue field is called "file".
- NEVER use "file_path".
- NEVER use "filename".
- NEVER use "path".
- The top-level field is called "recommendations".
- Do not omit "summary".
- Do not omit "overall_risk".
- Do not omit "recommendations".

If there are no issues, return exactly:

{
    "summary": "No significant issues were identified.",
    "overall_risk": "low",
    "issues": [],
    "recommendations": []
}
The response must contain the word "JSON".
"""


async def review_code(cleaned_diff: str) -> CodeReview:
    """
    Send a cleaned GitHub diff to the AI model for review.

    Parameters
    ----------
    cleaned_diff : str
        Cleaned GitHub pull request diff.

    Returns
    -------
    CodeReview
        Structured code review generated by the AI.
    """

    # Send the code diff to the AI model.
    #
    # We use the system message to define the reviewer's role
    # and the user message to provide the actual code changes.


    # Build the user message containing the actual code changes.
    user_prompt = f"""
    Review the following GitHub pull request diff.

    Analyze ONLY the code changes shown in this diff.

    For every issue you identify:

    - Provide the exact file path from the diff.
    - Provide the relevant line number if available.
    - Explain why the code is problematic.
    - Provide a concrete recommendation.

    If there are no meaningful issues, return an empty issues list.

    Return the result as JSON matching the CodeReview schema.

    PULL REQUEST DIFF:

    {cleaned_diff}
    """
    completion = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": user_prompt,
            },
        ],
        temperature=0,
        response_format={
            "type": "json_object"
        },
    )

    # Extract the model's response.
    response_content = completion.choices[0].message.content

    # Convert the JSON response into our Pydantic model.
    #
    # This validates that the AI returned the structure we expect.
    return CodeReview.model_validate_json(response_content)