"""
LLM service.

This module is responsible for communicating with the AI model.

The rest of our application does not need to know how Groq works.
It simply calls the review_code() function and receives a
structured CodeReview object.
"""

from groq import Groq

from app.config import settings
from app.models import CodeReview


# Create the Groq client using the API key stored in our
# application configuration.
client = Groq(
    api_key=settings.groq_api_key
)


# Model used for code review.
#
# We keep the model name in one place so it can easily be
# changed later without modifying the review logic.
MODEL_NAME = "llama-3.3-70b-versatile"


# System prompt defines the role and behaviour of our AI reviewer.
SYSTEM_PROMPT = """
You are an expert software engineer performing a code review.

You are reviewing a GitHub pull request diff.

Your task is to identify meaningful:

1. Bugs and incorrect behaviour
2. Security vulnerabilities
3. Performance problems
4. Poor coding practices
5. Maintainability issues
6. Error handling problems
7. Potential edge cases

Only report issues that are supported by the provided code.
Do not invent problems.

Prioritise real and actionable issues over minor stylistic preferences.

For every issue you identify, provide:

- severity
- category
- file
- line
- title
- description
- recommendation

Severity must be one of:

- critical
- high
- medium
- low

Category should be one of:

- security
- bug
- performance
- quality
- maintainability
- error_handling

IMPORTANT:

Your response MUST be a JSON object with EXACTLY this structure:

{
    "summary": "A short summary of the pull request",
    "overall_risk": "low",
    "issues": [
        {
            "severity": "high",
            "category": "security",
            "file": "app.py",
            "line": 3,
            "title": "Short issue title",
            "description": "Detailed explanation of the issue",
            "recommendation": "How the developer should fix the issue"
        }
    ],
    "recommendations": [
        "General recommendation"
    ]
}

The JSON object MUST contain all four top-level fields:

summary
overall_risk
issues
recommendations

Even when there are no issues, you MUST still return all four fields.

If there are no issues, return:

{
    "summary": "No significant issues were identified.",
    "overall_risk": "low",
    "issues": [],
    "recommendations": []
}

Do not omit any required field.

Return ONLY valid JSON.
"""


async def review_code(cleaned_diff: str) -> CodeReview:
    """
    Send a cleaned GitHub diff to the AI model for review.

    Parameters
    ----------
    cleaned_diff : str
        Cleaned GitHub pull request diff.

    Returns
    -------
    CodeReview
        Structured code review generated by the AI.
    """

    # Send the code diff to the AI model.
    #
    # We use the system message to define the reviewer's role
    # and the user message to provide the actual code changes.
    completion = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": (
                    "Review the following GitHub pull request diff:\n\n"
                    f"{cleaned_diff}"
                ),
            },
        ],
        temperature=0.1,
        response_format={
            "type": "json_object"
        },
    )

    # Extract the model's response.
    response_content = completion.choices[0].message.content

    # Convert the JSON response into our Pydantic model.
    #
    # This validates that the AI returned the structure we expect.
    return CodeReview.model_validate_json(response_content)