"""
Review formatting service.

Converts the structured CodeReview generated by the AI model
into a human-readable Markdown review suitable for GitHub.
"""

from app.models import CodeReview


def format_review_as_markdown(review: CodeReview) -> str:
    """
    Convert a structured CodeReview into Markdown.

    Parameters
    ----------
    review : CodeReview
        Structured review generated by the AI.

    Returns
    -------
    str
        Markdown-formatted GitHub review.
    """

    # Start with the overall summary.
    markdown = "# 🤖 AI Code Review\n\n"

    markdown += f"## Summary\n\n{review.summary}\n\n"

    # Display the overall risk.
    markdown += (
        f"**Overall Risk:** `{review.overall_risk.upper()}`\n\n"
    )

    # ---------------------------------------------------------
    # Issues
    # ---------------------------------------------------------

    if review.issues:

        markdown += "## Issues\n\n"

        for index, issue in enumerate(review.issues, start=1):

            markdown += (
                f"### {index}. {issue.title}\n\n"
            )

            markdown += (
                f"**Severity:** `{issue.severity.upper()}`  \n"
                f"**Category:** `{issue.category}`  \n"
                f"**File:** `{issue.file}`  \n"
            )

            if issue.line is not None:
                markdown += (
                    f"**Line:** `{issue.line}`  \n"
                )

            markdown += "\n"

            markdown += (
                f"**Description:** {issue.description}\n\n"
            )

            markdown += (
                f"**Recommendation:** {issue.recommendation}\n\n"
            )

    else:

        markdown += "## Issues\n\n"
        markdown += "No significant issues were identified. ✅\n\n"

    # ---------------------------------------------------------
    # General recommendations
    # ---------------------------------------------------------

    if review.recommendations:

        markdown += "## Recommendations\n\n"

        for recommendation in review.recommendations:
            markdown += f"- {recommendation}\n"

        markdown += "\n"

    # Add a small footer so users know this was generated
    # automatically.
    markdown += (
        "---\n\n"
        "*Generated by the AI Code Review Agent.*"
    )

    return markdown