from typing import List
# Import BaseModel for creating structured request/response models
# and HttpUrl for validating that a value is a valid HTTP/HTTPS URL.
from pydantic import BaseModel, HttpUrl


class ReviewRequest(BaseModel):
    """
    Request body for the /review endpoint.

    The frontend will eventually send a GitHub pull request URL.
    """

    # GitHub Pull Request URL that the user wants reviewed.
    pr_url: HttpUrl


class ReviewIssue(BaseModel):
    """
    Represents one issue identified during code review.
    """

    # Severity of the issue.
    #
    # Examples:
    # critical, high, medium, low
    severity: str

    # Category of the issue.
    #
    # Examples:
    # security, bug, performance, quality
    category: str

    # File where the issue was identified.
    file: str

    # Approximate line number associated with the issue.
    line: int | None = None

    # Short description of the problem.
    title: str

    # Detailed explanation of why the issue matters.
    description: str

    # Suggested way of addressing the issue.
    recommendation: str


class CodeReview(BaseModel):
    """
    Structured response generated by the AI code reviewer.
    """

    # Overall summary of the pull request.
    summary: str

    # Overall risk assessment.
    overall_risk: str

    # Individual issues discovered during the review.
    issues: List[ReviewIssue]

    # General recommendations that are not necessarily associated with one specific issue.
    recommendations: List[str]