from typing import List

from pydantic import BaseModel, HttpUrl


class ReviewRequest(BaseModel):
    """Request body for the /review endpoint."""

    pr_url: HttpUrl


class ReviewIssue(BaseModel):
    """Represents one issue identified during code review."""

    severity: str
    category: str
    file: str
    line: int | None = None
    title: str
    description: str
    recommendation: str


class CodeReview(BaseModel):
    """Structured response generated by the AI code reviewer."""

    summary: str
    overall_risk: str
    issues: List[ReviewIssue]
    recommendations: List[str]


class ReviewResponse(BaseModel):
    """Response returned after reviewing a public GitHub pull request."""

    review: CodeReview

    # Present when the agent successfully posts the review to GitHub.
    # It is optional because reviewing a public repository does not
    # require write access to that repository.
    github_review_url: str | None = None

    # True when the AI review was also posted to GitHub.
    github_review_posted: bool = False

    # Human-readable explanation of the GitHub posting status.
    github_message: str
